Document: check-virtsys
Title: Debian check-virtsys Manual
Author: <insert document author here>
Abstract: This manual describes what check-virtsys is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/check-virtsys/check-virtsys.sgml.gz

Format: postscript
Files: /usr/share/doc/check-virtsys/check-virtsys.ps.gz

Format: text
Files: /usr/share/doc/check-virtsys/check-virtsys.text.gz

Format: HTML
Index: /usr/share/doc/check-virtsys/html/index.html
Files: /usr/share/doc/check-virtsys/html/*.html
